packages:
  - apps/*
  - packages/*

catalog:
  '@apollo/cache-control-types': ^1.0.3
  '@apollo/server': ^5.0.0
  '@apollo/server-plugin-response-cache': ^5.0.0
  '@as-integrations/next': ^4.0.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@formkit/auto-animate': ^0.9.0
  '@headlessui/react': ^2.2.8
  '@heroicons/react': ^2.2.0
  '@hookform/resolvers': ^5.2.2
  '@iconify/react': ^6.0.2
  '@libsql/client': 0.15.15
  '@paralleldrive/cuid2': 2.2.2
  '@radix-ui/react-select': ^2.2.6
  '@tailwindcss/postcss': ^4.1.13
  '@tanstack/react-query': 5.89.0
  '@upstash/redis': ^1.35.4
  argon2: 0.31.2
  axios: 1.12.2
  class-validator: ^0.14.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  common-tags: 1.8.2
  cors: ^2.8.5
  critters: ^0.0.25
  date-fns: ^4.1.0
  dotenv: ^17.2.2
  drizzle-orm: 0.44.5
  framer-motion: ^12.23.16
  fuse.js: ^7.1.0
  genius-lyrics-api: ^3.2.1
  get-artist-title: ^1.3.1
  get-youtube-id: ^1.0.1
  graphql: ^16.11.0
  graphql-request: 7.2.0
  immer: ^10.1.3
  is-mobile: ^5.0.0
  lexorank: ^1.0.5
  lodash: ^4.17.21
  lru-cache: ^11.2.1
  lucide-react: ^0.544.0
  micro: ^10.0.1
  next: ^15.5.3
  next-nprogress-bar: ^2.4.7
  next-seo: ^6.8.0
  pino: 9.11.0
  react: 19.1.1
  react-dom: 19.1.1
  react-hook-form: 7.63.0
  react-hotkeys-hook: ^5.1.0
  react-player: 2.16.0
  reflect-metadata: ^0.2.2
  simplebar-core: ^1.3.2
  simplebar-react: ^3.3.2
  sonner: 2.0.7
  soundcloud.ts: ^0.6.5
  spotify-uri: ^4.1.0
  spotify-url-info: ^3.2.18
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.3.8
  type-graphql: 2.0.0-rc.2
  undici: ^7.16.0
  usehooks-ts: ^3.1.1
  valibot: ^1.1.0
  youtubei: ^1.7.0
  zustand: ^5.0.8
  '@next/eslint-plugin-next': ^15.5.3
  '@tailwindcss/typography': ^0.5.18
  '@testing-library/react': ^16.3.0
  '@types/common-tags': ^1.8.4
  '@types/cors': ^2.8.19
  '@types/lodash': ^4.17.20
  '@types/micro-cors': ^0.1.5
  '@types/node': 22.9.0
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  '@vitejs/plugin-react': ^5.0.3
  autoprefixer: ^10.4.21
  drizzle-kit: ^0.31.4
  graphql-tag: ^2.12.6
  jsdom: ^27.0.0
  pino-pretty: ^13.1.1
  postcss: 8.5.6
  swd-eslint-config: ^2.2.0
  tailwindcss: 4.1.13
  typescript-eslint: ^8.44.0
  vitest: ^3.2.4
  eslint: ^9.36.0
  typescript: ^5.9.2
  prettier: ^3.6.2
  turbo: ^2.5.6
  es-toolkit: ^1.39.10
  better-auth: ^1.3.14
  "@orpc/server": ^1.8.9
  arktype: ^2.1.22
  radix-ui: ^1.4.3
  react-use-measure: ^2.1.7
  motion: ^12.23.21