query getAlbumsQuery($artist: String!, $limit: Int!) {
  getAlbums(artist: $artist, limit: $limit, page: 1) {
    artist
    coverImage
    description
    genre
    name
    tracks
    year
    albumId
  }
}
