query playlistQuery($playlistId: ID!) {
  playlist(playlistId: $playlistId) {
    id
    name
    type
    songs {
      id
      title
      artist
      songUrl
      rank
      createdAt
    }
    user {
      id
      name
    }
  }
}
