name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read pnpm version from package.json
        id: pnpm-version
        run: |
          echo "version=$(jq -r '.packageManager | split("@")[1]' package.json)" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run tsc
